### ISSUE TITLE
[joss-review] memory requirement of example run

### ISSUE THREAD

**Issue by zonca** [PSims/BayesEoR#22]
the first step of the analysis requires about 20 GB of RAM, it would be useful to specify it in the docs, I ran with 15 GB and the process was killed (probably for out of memory)

I'll also estimate memory requirement for the second step and add it here.

**Comment by jburba** [comment]
I've updated the "Test Dataset" docs under `usage.rst` with RAM requirements ([b9af6b5](https://github.com/PSims/BayesEoR/commit/b9af6b50f5de79073519380d2dd9543347536d1a)).  When I ran the test dataset on a slurm system, I see the matrix construction step required ~17 GB of RAM according to the MaxRSS column in the slurm database and the power spectrum analysis required ~12 GB of RAM.  The requirement for the matrix construction being ~17 GB is probably why your job was killed with 15 GB of RAM but succeeded with 20 GB.

**Comment by zonca** [comment]
it seems like the docs website is not automatically updating:
https://bayeseor.readthedocs.io/en/latest/usage.html#running-the-power-spectrum-analysis

as you estimated the power spectrum requirement for power spectrum analysis, I think it would be a good idea to add that number in.
Do you also know how much GPU memory is needed?

**Comment by jburba** [comment]
Ah, yes.  I had to manually rebuild the docs (I haven't automated the docs building yet).  The documentation should be updated now.

Regarding GPU memory, I believe the routing we are using in MAGMA is capable of partial i/o so it should be capable of running on a wide range of hardware.
