### ISSUE TITLE
[joss-review] Feedback on paper

### ISSUE THREAD

**Issue by zonca** [PSims/BayesEoR#25]
## Statement of need

- [x] Please explain where the 21-cm emission comes from
- [x] Gyr is too technical for the statement of need

## Summary

Just a bit more details on the process

- [x] it would be useful to specify what parameters of an instrument you can characterize
- [x] also specify what is the format of the input data, are those timelines of some sort?
- [x] do you generally run this full-sky or works in patches?
- [x] do you use any other inputs besides instrument parameters and instrument data?

## Figure 1

Explain terminology

- [x] phi
- [x] k
- [x] $\Delta K$

**Comment by zonca** [comment]
also "Do the authors describe how this software compares to other commonly-used packages?", aren't there other codes doing something similar?

**Comment by jburba** [comment]
Hi @zonca , I think I've addressed your suggestions.  Please give the paper a read and let me know what you think.  I've also updated the documentation to include some more information about the inputs and more detail on running the analysis.

**Comment by zonca** [comment]
text is good, can you explain the terminology in the figure? best would be to add a caption.
